"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bitcoin-wallet.py']
APP_NAME = "BitSee"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'bitcoin.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Tracking bitcoin wallets since 2015",
        'CFBundleIdentifier': "com.jamescampbell.osx.ballet",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2015, James Campbell, All Rights Reserved"
        }
    }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
